// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBBdFTAbMOKKwuqcE2slG-Js9JvzcHi_A',
    appId: '1:924584562316:web:7ea6468104534c4c9e75a9',
    messagingSenderId: '924584562316',
    projectId: 'chatapp-a3787',
    authDomain: 'chatapp-a3787.firebaseapp.com',
    storageBucket: 'chatapp-a3787.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDH3j1GTPIaBmPLSSWcfNSAf0uunXFQ4I',
    appId: '1:924584562316:android:0462b8c84a5742a59e75a9',
    messagingSenderId: '924584562316',
    projectId: 'chatapp-a3787',
    storageBucket: 'chatapp-a3787.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTUtM_Vnvte5BzfdCa_lxQc3tip4Zkpqk',
    appId: '1:924584562316:ios:978d8d9efe3e7ab09e75a9',
    messagingSenderId: '924584562316',
    projectId: 'chatapp-a3787',
    storageBucket: 'chatapp-a3787.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTUtM_Vnvte5BzfdCa_lxQc3tip4Zkpqk',
    appId: '1:924584562316:ios:978d8d9efe3e7ab09e75a9',
    messagingSenderId: '924584562316',
    projectId: 'chatapp-a3787',
    storageBucket: 'chatapp-a3787.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBBdFTAbMOKKwuqcE2slG-Js9JvzcHi_A',
    appId: '1:924584562316:web:960bb0bf9549f97a9e75a9',
    messagingSenderId: '924584562316',
    projectId: 'chatapp-a3787',
    authDomain: 'chatapp-a3787.firebaseapp.com',
    storageBucket: 'chatapp-a3787.appspot.com',
  );
}
